name: lab02 # Can be changed
on:
  push
  #:
  #  branches:
  #    - 'main'
  #  paths:
  #    - ./'labs/02/**'
jobs:
  run: # Can be changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - run: pip install -r requirements.txt
      - run: python -m nbconvert --to pdf --execute ./labs/02/02.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: ./labs/02/02.pdf  # Add caching to github actions
