name: lab01 # Can be changed
on: push
jobs:
  test: # Can be changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # USe latest
      - run: pip install nbconvert
      - run: python -m nbconvert --to pdf ./notes/pint_and_boiling_point.ipynb