name: lab01 # Can be changed
on: push
jobs:
  test: # Can be changed
    runs-on: ubuntu-latest
    steps:
      - run: pip install nbconvert
      - run: python -m nbconvert ./notes/pint_and_boiling_point.ipynb