name: lab01 # Can be changed
on: push
jobs:
  test: # Can be changed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python -m nbconvert --to pdf --execute ./labs/02.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: notes/pint_and_boiling_point.pdf  # Add caching to github actions
