name: lab07
on:
  push:
    branches:
      - 'main'
    paths:
      - 'labs/07/**'
      - '.github/workflows/lab07.yml'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Build LAB 07 Homework .PDF Artifact
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: ./requirements.txt
      - run: pip install -r ./requirements.txt
      - run: python -m nbqa pylint ./labs/07/assigment.ipynb
      - run: python -m nbconvert --to pdf --execute ./labs/07/assigment.ipynb
      - uses: actions/upload-artifact@v4
        with:
          name: dominik_breksa_lab07_assigment
          path: ./labs/07/assigment.pdf
