name: lab04
on:
  push:
    branches:
      - 'main'
    paths:
      - 'labs/04/**'
      - '.github/workflows/lab04.yml'
jobs:
  run:
    runs-on: ubuntu-latest
    name: Build LAB 04 Homework .PDF Artifact
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get update
      - run: sudo apt-get install pandoc inkscape texlive-xetex
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: ./requirements.txt
      - run: pip install -r ./requirements.txt
      - run: python -m nbconvert --to pdf --execute ./labs/04/assigment.ipynb
      - uses: actions/upload-artifact@v4
        with:
          path: ./labs/04/assigment.pdf
